Algoritmo "exeh"

Var

compri, larg, alt, vol : real

Inicio

escreva ("Qual o comprimento da caixa retangular em cm? ")
        leia (compri)
escreva ("Qual a largura da caixa retangular em cm? ")
        leia (larg)
escreva ("Qual a altura da caixa retangular em cm? ")
        leia (alt)

vol <- alt*larg*compri

escreva ("O volume total da caixa retangular com as medidas informadas é: ", vol)

Fimalgoritmo