Algoritmo "exem"

var

cot, brl, usd : real

Inicio

escreva ("Digite a cotação do dolar no momento: ")
        leia (cot)
escreva ("Qual será o valor convertido em dólares? ")
        leia (usd)

brl <- (usd*cot)

escreval ("Levando em consideração a cotação digitada")
escreval ("e o valor de", usd,"US$ que serão convertidos")
escreval ("o valor que você terá disponível em Reais será de:")
escreval (brl,"R$")

Fimalgoritmo
